language: java
os: linux
dist: xenial
jdk:
- openjdk8
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
addons:
  ssh_known_hosts:
    - 39.106.230.88

branches:
  only:
  - main
script: mvn clean package -Dmaven.test.skip=true

before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host yzhelp.top\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- scp -o stricthostkeychecking=no -r target/campus-recruitment-guidance-0.0.1-SNAPSHOT.jar travis@yzhelp.top:/www/wwwroot/travis-app/campus-recruitment-guidance
- ssh travis@yzhelp.top -o stricthostkeychecking=no "sh /www/wwwroot/travis-app/campus-recruitment-guidance/restart.sh"

notifications:
  email:
  - gongsir0630@gmail.com
