spring:
  application:
    name: campus-recruitment-guidance
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    servlet:
      content-type: text/html
    enabled: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  # 配置文件环境
  profiles:
    active: ${spring.profiles.active}

# 设置日志级别
logging:
  level:
    org.springframework.web: info
    top.yzhelp.campus: debug

# 微信小程序配置
wx:
  appid: wx2e1d0d6fb608404c
  url: http://miniapp.yzhelp.top/wx